{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/CallDelegate\/call(_:didFail:)"},"metadata":{"role":"symbol","externalID":"s:10AXPCalling12CallDelegateP4call_7didFailyAA0B0C_s5Error_ptF","title":"call(_:didFail:)","symbolKind":"method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"call","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10AXPCalling4CallC","text":"Call"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"AXPCalling"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"call"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"call","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/Call","kind":"typeIdentifier","preciseIdentifier":"s:10AXPCalling4CallC","text":"Call"},{"text":", ","kind":"text"},{"text":"didFail","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This is a fatal error and the call will end, calling ","type":"text"},{"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/CallDelegate\/callDidEnd(_:)","type":"reference","isActive":true},{"text":". A","type":"text"},{"type":"text","text":" "},{"text":"call can fail while it is connecting or at any point after it has","type":"text"},{"type":"text","text":" "},{"type":"text","text":"connected due to an unrecoverable error."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/axpcalling\/calldelegate\/call(_:didfail:)"]}],"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling","doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/CallDelegate"]]},"abstract":[{"type":"text","text":"Tells the delegate that the call has failed."}],"references":{"doc://com.avaya.axp.omni.sdk.AXPCalling/documentation/AXPCalling/CallDelegate/callDidEnd(_:)":{"required":true,"title":"callDidEnd(_:)","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/CallDelegate\/callDidEnd(_:)","type":"topic","url":"\/documentation\/axpcalling\/calldelegate\/calldidend(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callDidEnd"},{"text":"(","kind":"text"},{"text":"Call","kind":"typeIdentifier","preciseIdentifier":"s:10AXPCalling4CallC"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the call has ended."}],"kind":"symbol"},"doc://com.avaya.axp.omni.sdk.AXPCalling/documentation/AXPCalling/Call":{"type":"topic","url":"\/documentation\/axpcalling\/call","kind":"symbol","title":"Call","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Call"}],"abstract":[{"text":"A realtime audio call between the local device and your call center.","type":"text"}],"navigatorTitle":[{"text":"Call","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/Call"},"doc://com.avaya.axp.omni.sdk.AXPCalling/documentation/AXPCalling/CallDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallDelegate"}],"navigatorTitle":[{"text":"CallDelegate","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An interface that communicates changes to a callâ€™s state."}],"title":"CallDelegate","kind":"symbol","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/CallDelegate","url":"\/documentation\/axpcalling\/calldelegate"},"doc://com.avaya.axp.omni.sdk.AXPCalling/documentation/AXPCalling":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"Make audio calls using the Avaya Experience Platform."}],"kind":"symbol","title":"AXPCalling","url":"\/documentation\/axpcalling","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling"},"doc://com.avaya.axp.omni.sdk.AXPCalling/documentation/AXPCalling/CallDelegate/call(_:didFail:)":{"role":"symbol","title":"call(_:didFail:)","kind":"symbol","abstract":[{"text":"Tells the delegate that the call has failed.","type":"text"}],"required":true,"url":"\/documentation\/axpcalling\/calldelegate\/call(_:didfail:)","type":"topic","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCalling\/documentation\/AXPCalling\/CallDelegate\/call(_:didFail:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"call","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Call","kind":"typeIdentifier","preciseIdentifier":"s:10AXPCalling4CallC"},{"text":", ","kind":"text"},{"text":"didFail","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]}}}