{"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/errorDescription"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"errorDescription","role":"symbol","externalID":"s:7AXPCore8AXPErrorO16errorDescriptionSSSgvp","modules":[{"name":"AXPCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/axpcore\/axperror\/errordescription"]}],"sections":[],"references":{"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore":{"url":"\/documentation\/axpcore","title":"AXPCore","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user."}],"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError/errorDescription":{"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/errorDescription","abstract":[],"url":"\/documentation\/axpcore\/axperror\/errordescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","role":"symbol","title":"errorDescription"},"doc://com.avaya.axp.client.sdk.AXPCore/documentation/AXPCore/AXPError":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AXPError","kind":"identifier"}],"identifier":"doc:\/\/com.avaya.axp.client.sdk.AXPCore\/documentation\/AXPCore\/AXPError","navigatorTitle":[{"text":"AXPError","kind":"identifier"}],"url":"\/documentation\/axpcore\/axperror","title":"AXPError","abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"type":"text","text":" "},{"type":"text","text":"across the network."}],"role":"symbol","kind":"symbol"}}}