{"abstract":[{"type":"text","text":"If internal error"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/axpcore\/axperror\/internalerror"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError"},"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"AXPCore"}],"externalID":"s:7AXPCore8AXPErrorO13internalErroryA2CmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"title":"AXPError.internalError","symbolKind":"case"},"references":{"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError/internalError":{"type":"topic","abstract":[{"type":"text","text":"If internal error"}],"kind":"symbol","url":"\/documentation\/axpcore\/axperror\/internalerror","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/internalError","title":"AXPError.internalError"},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore":{"abstract":[{"type":"text","text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user."}],"role":"collection","title":"AXPCore","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","url":"\/documentation\/axpcore","type":"topic","kind":"symbol"},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"text":" ","type":"text"},{"type":"text","text":"across the network."}],"url":"\/documentation\/axpcore\/axperror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AXPError","kind":"identifier"}],"title":"AXPError","navigatorTitle":[{"text":"AXPError","kind":"identifier"}],"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError","kind":"symbol"}}}