{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidData"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/axpcore\/axperror\/invaliddata"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/invalidData"},"abstract":[{"text":"If the received data was invalid","type":"text"}],"sections":[],"metadata":{"externalID":"s:7AXPCore8AXPErrorO11invalidDatayA2CmF","role":"symbol","symbolKind":"case","title":"AXPError.invalidData","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidData","kind":"identifier"}],"modules":[{"name":"AXPCore"}],"roleHeading":"Case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore":{"title":"AXPCore","kind":"symbol","identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore","abstract":[{"text":"The base module that establishes the session with Avaya Experience Platformâ„¢ (AXP) for the end user.","type":"text"}],"url":"\/documentation\/axpcore","role":"collection","type":"topic"},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError":{"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError","kind":"symbol","title":"AXPError","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXPError","kind":"identifier"}],"navigatorTitle":[{"text":"AXPError","kind":"identifier"}],"url":"\/documentation\/axpcore\/axperror","abstract":[{"type":"text","text":"Error for the case where an operation failed due to an error contacting AXP"},{"text":" ","type":"text"},{"text":"across the network.","type":"text"}]},"doc://com.avaya.axp.omni.sdk.AXPCore/documentation/AXPCore/AXPError/invalidData":{"kind":"symbol","url":"\/documentation\/axpcore\/axperror\/invaliddata","abstract":[{"text":"If the received data was invalid","type":"text"}],"role":"symbol","type":"topic","title":"AXPError.invalidData","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidData"}],"identifier":"doc:\/\/com.avaya.axp.omni.sdk.AXPCore\/documentation\/AXPCore\/AXPError\/invalidData"}}}